name = "catafalque"
license = "MIT"
licenselink = "https://github.com/SeriousBug/hugo-theme-catafalque/blob/master/LICENSE.md"
description = "A lightweight Hugo theme, for personal blogs and landing pages."
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.30

[author]
  name = "Kaan Barmore-Genc"
  homepage = "https://bgenc.net"

[original]
  name = "hello-friend"
  homepage = "https://github.com/panr/hugo-theme-hello-friend"
  repo = "https://github.com/panr/hugo-theme-hello-friend"
